name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      PORT: ${{ secrets.PORT }}
      TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
      REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
      REGISTER_SERVICE_SECRET: ${{ secrets.REGISTER_SERVICE_SECRET }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        cat <<EOF > .env
        TOKEN_SECRET=${TOKEN_SECRET}
        PORT=${PORT}
        REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
        REGISTER_SERVICE_SECRET=${REGISTER_SERVICE_SECRET}
        EOF
        docker build -t auth-microservices:1.0.0 .

    - name: Tag Docker image
      run: docker tag auth-microservices:1.0.0 "${{ secrets.DOCKER_USERNAME }}/auth-microservices:1.0.0"

    - name: Push Docker image
      run: docker push "${{ secrets.DOCKER_USERNAME }}/auth-microservices:1.0.0"

    - name: Clean up temporary files
      run: |
        # Remove temporary Docker image
        docker rmi auth-microservices:1.0.0

        # Remove Docker image tag
        docker rmi "${{ secrets.DOCKER_USERNAME }}/auth-microservices:1.0.0"
