name: Staging CICD

on:
  push:
    branches: [staging/init]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t soyaslimbu/dev-auth-microservices .
      - name: Publish image to docker hub
        run: docker push soyaslimbu/dev-auth-microservices:latest

  deploy:
    needs: build
    runs-on: [dev-auth-runner]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Pull image from Docker Hub
        run: sudo docker-compose -f /opt/docker-compose.yml pull

      - name: Stop and remove old containers
        run: sudo docker-compose -f /opt/docker-compose.yml down

      - name: Run Docker Compose in production
        run: sudo docker-compose -f /opt/docker-compose.yml up -d